dataset1:
  name: customBulkData
  display: customBulkData
  data: none
  svg: none
dataset2:
  name: customCovisData
  display: customCovisData
  data: none
  svg: none
dataset3:
  name: mouse_Merkin
  display: Mouse organs (SHM, Merkin)
  data: data/expr_mouse.txt
  svg: data/mus_musculus.male.svg
dataset4:
  name: covis_Ortiz_Vacher
  display: Mouse brain (covisualization, Ortiz, Vacher)
  data: data/shiny_covis_bulk_cell_mouse_brain.rds
  svg: data/mus_musculus.brain.svg
dataset5:
  name: brain_Prudencio
  display: Human brain (SHM, Prudencio)
  data: data/expr_human.txt
  svg: data/homo.sapiens_brain.shiny_shm.svg
dataset6:
  name: chicken_Cardoso.Moreira
  display: Chicken organs (SHM, Cardoso.Moreira)
  data: data/expr_chicken.txt
  svg: data/gallus_gallus.svg
dataset7:
  name: shoot_Mustroph
  display: Arabidopsis shoot (SHM, Mustroph)
  data: data/expr_arab.txt
  svg: data/arabidopsis.thaliana_shoot_shm.svg
dataset8:
  name: organ_Mustroph
  display: Arabidopsis organs (SHM, Mustroph)
  data: data/expr_arab.txt
  svg: data/arabidopsis.thaliana_organ_shm.svg
dataset9:
  name: root_Mustroph
  display: Arabidopsis root (SHM, Mustroph)
  data: data/expr_arab.txt
  svg: data/arabidopsis.thaliana_root.cross_shm.svg
dataset10:
  name: shootRoot_Mustroph
  display: Arabidopsis shoot/root (SHM, Mustroph)
  data: data/expr_arab.txt
  svg: data/arabidopsis.thaliana_shoot.root_shm.svg
dataset11:
  name: rootRootTip_Mustroph
  display: Arabidopsis root/rootTip (SHM, Mustroph)
  data: data/expr_arab.txt
  svg: data/arabidopsis.thaliana_root.roottip_shm.svg
dataset12:
  name: multiVariables_Attilio
  display: Multiple variables (SHM, Attilio)
  data: data/mus_brain_vars.txt
  svg: data/mus_musculus.brain.svg
dataset13:
  name: growthStage_Mustroph
  display: Multiple aSVGs (SHM, Mustroph)
  data: data/random_data_multiple_aSVGs.txt
  svg:
  - data/arabidopsis.thaliana_organ_shm1.svg
  - data/arabidopsis.thaliana_organ_shm2.svg
dataset14:
  name: overlay
  display: Overlaying (SHM, Bezrutczyk)
  data: data/dat_overlay.txt
  svg:
  - data/maize_leaf_shm1.png
  - data/maize_leaf_shm1.svg
  - data/maize_leaf_shm2.png
  - data/maize_leaf_shm2.svg
title:
- title:spatialHeatmap
- width:350
max.upload.size: 5G 
default.dataset: mouse_Merkin
col.row.gene: None
separator: None
# Settings for Data Table on the Spatial Heatmap panel.
data.matrix:
- norm:CNF-TMM
- A:0
- P:0
- CV1:-10000
- CV2:10000
- log.exp:No
- scale:No
- selected.id:Tbx2
# Settings for spatial heatmaps on the Spatial Heatmap panel.
shm.img:
- columns:2
- display.by:gene
- scale.plots:1.1
- title.size:12
- relative.size:1
- color:yellow,orange,red
- color.scale:Selected rows
- file.type:jpg
- dpi:300
- include.legend.plot:Yes
- legend.plot.size:0.8
- value.legend.rows:1
- value.legend.key:0.03
- value.legend.text:10
- include.feature:No
- line.color:grey70
- line.size:0.1
shm.anm:
- show:No
- transition:2
- scale.plot:1
shm.video:
- show:No
- transition:1
- dpi:400
- key.rows:2
- key.size:0.04
- value.legend:No
- feature.label:No
- label.size:2
- dimension:640x480
- bar.width.video:0.07
legend:
- key.row:3
- key.size:0.04
- label:No
- label.size:2.5
- aspect.ratio:1
mhm:
- measure:Correlation
- cor.absolute:No
- select.by:p
- cutoff:0.2
- scale:No
network:
- color:yellow,orange,red
- net.type:signed
- min.size:15
- ds:3
- max.edges:10
download_single:
  data: data/expr_arab.txt
  svg: data/arabidopsis.thaliana_shoot_shm.svg
download_multiple:
  data: data/random_data_multiple_aSVGs.txt
  svg:
  - data/arabidopsis.thaliana_organ_shm1.svg
  - data/arabidopsis.thaliana_organ_shm2.svg
download_multiple_variables:
  data: data/expr_coleoptile_samTimeCon.txt
  svg: data/oryza.sativa_coleoptile.ANT_shm.svg
download_covisualization:
  data:
  - data/shiny_covis_bulk_cell_mouse_brain.rds
  svg: data/mus_musculus.brain.svg
download_batched_data_aSVGs:
  data: data/aSVGs_shm.tar
  svg: data/data_shm.tar
